name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [ closed ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Run code generation (if needed)
      run: |
        if grep -q "build_runner" pubspec.yaml; then
          flutter packages pub run build_runner build --delete-conflicting-outputs
        fi

    - name: Build APK
      run: flutter build apk --release

    - name: Rename APK for release
      run: |
        APK_NAME="clock-sessions-v${{ github.run_number }}.apk"
        cp build/app/outputs/flutter-apk/app-release.apk "$APK_NAME"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: clock-sessions-v${{ github.run_number }}
        path: clock-sessions-v${{ github.run_number }}.apk
        retention-days: 30

    - name: Create Release and Upload APK
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="v${{ github.run_number }}"
        RELEASE_NAME="Release v${{ github.run_number }}"
        APK_NAME="clock-sessions-v${{ github.run_number }}.apk"

        gh release create "$TAG_NAME" "$APK_NAME" \
          --title "$RELEASE_NAME" \
          --notes "Automated release created from commit ${{ github.sha }}

        Changes in this release:
        ${{ github.event.head_commit.message }}"
